registroBibliotecario/urls.py
from django.contrib import admin
from django.urls import path
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #--------------------USER MANAGE-------------------------
    path('', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    #-----------------------BOOKS-----------------------
    path('books/home/', views.books, name='books'),
    path('books/<int:idBook>/', views.bookDetails, name='bookDetails'),
    path('books/<int:idBook>/deleteBook/', views.deleteBook, name='deleteBook'),
    path('books/addBook/', views.addBook, name='addBook'),
    #-----------------READERS-------------
    path('readers/home/', views.readers, name='readers'),
    path('readers/<int:idReader>/', views.readerDetails, name='readerDetails'),
    path('readers/<int:idReader>/deleteReader/', views.deleteReader, name='deleteReader'),
    path('reader/addReader/', views.addReader, name='addReader'),
    #----------------LOANS-------------------------------
    path('loans/<int:idReader>/createLoan', views.createLoan, name='createLoan'),
    path('loans/home/', views.loans, name='loans'),
    path('loans/<int:idLoan>/', views.loanDetails, name='loanDetails'),
    path('loans/<int:idBook>/<int:idReader>/saveLoan/', views.saveLoan, name='saveLoan'),
    path('loans/<int:idLoan>/loanComeback/', views.loanComeback, name='loanComeback')
]

app/models.py
from django.db import models

class Books(models.Model):
    titulo = models.CharField(max_length=40)
    editorial = models.CharField(max_length=100)
    autor = models.CharField(max_length=30)
    fechaEntrada = models.DateField(null=True, blank=True)
    tipoAdquisicion = models.CharField(max_length=40)
    edicion = models.CharField(max_length=40)
    disponible = models.BooleanField(default=True)
    def __str__(self):
        return f'{self.titulo}'

class Readers(models.Model):
    nombres = models.CharField(max_length=60)
    apellidos = models.CharField(max_length=60)
    año = models.CharField(max_length=10, blank=True, null=True)
    seccion = models.CharField(max_length=20, blank=True, null=True)
    especialidad = models.CharField(max_length=40, blank=True, null=True)
    email = models.CharField(max_length=100)
    numeroTelefono = models.IntegerField()
    direccion = models.CharField(max_length=150, blank=True, null=True)
    esDocente = models.BooleanField(default=False)

    YEAR_CHOICES = (
        ('1','1'),
        ('2','2'),
        ('3','3'),
    )

    SECCION_CHOICES = (
        ('A', 'A'),
        ('B', 'B'),
        ('C','C'),
        ('D','D'),
        ('E','E')
    )

    ESPECIALIDADES_CHOICES = (
        ('Administrativo contable', 'Administrativo contable'),
        ('General', 'General'),
        ('Desarrollo de software', 'Desarrollo de software'),
        ('Serviempresa', 'Serviempresa'),
        ('Docente', 'Docente')
    )



class Loans(models.Model):
    idLibro = models.ForeignKey(Books, on_delete=models.CASCADE)
    idLector = models.ForeignKey(Readers, on_delete=models.CASCADE)
    fechaPrestamo = models.DateField(auto_now_add=True)
    fechaEntrega = models.DateField(null=True)
    estado = models.BooleanField(default=True)

app/templates/books/addBook.html
{% extends 'base/base.html' %}

{% block content %}
    {% load static %}
    <header>
        <h1 class="title-page">Añadir Libro</h1>
        <nav class="nav">
            <ul class="nav-box">
                <li >
                    <a href="{% url 'books' %}" class="nav-box__items item-menu-activate">Volver</a>
                </li>
            </ul>
        </nav>
    </header>

    <div class="div-container-addForm background_filter">
        <form method="POST" action="{% url 'addBook' %}" class="container-addForm background_filter">
            {% csrf_token %}
            {{error}}
            <div class="content">
                <div class="container-addForm--inputs">
                    <label for="id_titulo" class="container-addForm--inputs__label">Titulo</label>
                    <div class="border">
                        {{form.titulo}}
                    </div>
                </div>
                <div class="container-addForm--inputs">
                    <label for="id_editorial" class="container-addForm--inputs__label">Editorial</label>
                    <div class="border">
                        {{form.editorial}}
                    </div>
                </div>
                
                <div class="container-addForm--inputs">
                    <label for="id_autor" class="container-addForm--inputs__label">Autor</label>
                    <div class="border">
                        {{form.autor}}
                    </div>
                </div>
                <div class="container-addForm--inputs">
                    <label for="id_tipoAdquisicion" class="container-addForm--inputs__label">Tipo de adquisicion</label>
                    <div class="border">
                        {{form.tipoAdquisicion}}
                    </div>
                </div>
                
                <div class="container-addForm--inputs">
                    <label for="id_edicion" class="container-addForm--inputs__label">Edicion</label>
                    <div class="border">
                        {{form.edicion}}
                    </div>
                </div>
                <div class="container-addForm--inputs">
                    <label for="id_edicion" class="container-addForm--inputs__label">Puesto en circulacion</label>
                    <div class="border">
                        <div class="center-items">{{form.fechaEntrada}}</div>
                    </div>
                </div>
            </div>
            <div class="container-addForm--inputs space-between">
                <button class="container-form__button center-items color-update">
                    Añadir
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M3 8v11c0 2.201 1.794 3 3 3h15v-2H6.012C5.55 19.988 5 19.806 5 19c0-.101.009-.191.024-.273.112-.576.584-.717.988-.727H21V4c0-1.103-.897-2-2-2H6c-1.206 0-3 .799-3 3v3zm3-4h13v12H5V5c0-.806.55-.988 1-1z"></path><path d="M11 14h2v-3h3V9h-3V6h-2v3H8v2h3z"></path></svg>
                </button>
                <div class="center-items">
                    <label for="" class="style-label">agregar fecha de ahora</label> 
                    <input class="style-check" type="checkbox" name="dateToday" id="">
                </div>
            </div>
        </form>
    </div>
{% endblock %}

app/templates/books/bookDetails.html
{% extends 'base/base.html' %}
{% block content %}
    {% load static %}
    <header>
        <h1 class="title-page__addBook">{{title}}</h1>
        <nav>
            <ul class="nav-box">
            <li><a href="{% url 'books' %}" class="nav-box__items item-menu-activate">Volver</a></li>
            </ul>
        </nav>
    </header>
    <div class="div-container-addForm background_filter"> 
        <div class="space-between">
            <div class="align-end center-items">
                {% if loan %}
                <a href="{% url 'loanDetails' loan.id %}" class="cta">Ver prestamo</a>  
                {% endif %}
                <label for=""> veces prestado: {{leido}} </label>
            </div>
                
            <form action="{% url 'deleteBook' book.id %}" method="POST" class="align-end">
                {% csrf_token %}
                <button class="container-form__button color-delete center-items">
                    Eliminar
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(202, 202, 202, 0.747)"><path d="M6 7H5v13a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V7H6zm4 12H8v-9h2v9zm6 0h-2v-9h2v9zm.618-15L15 2H9L7.382 4H3v2h18V4z"></path></svg>
                </button>
            </form>
        </div>
        <form method="POST" action="" class="container-addForm">
            {% csrf_token %}
            {{error}}
            <div class="content">
                <div class="container-addForm--inputs">
                    <label for="id_titulo" class="container-addForm--inputs__label">Titulo</label>
                    <div class="border">
                        {{form.titulo}}
                    </div>
                </div>
                <div class="container-addForm--inputs">
                    <label for="id_editorial" class="container-addForm--inputs__label">Editorial</label>
                    <div class="border">
                        {{form.editorial}}
                    </div>
                </div>
                <div class="container-addForm--inputs">
                    <label for="id_autor" class="container-addForm--inputs__label">Autor</label>
                    <div class="border">
                        {{form.autor}}
                    </div>
                </div>
                <div class="container-addForm--inputs">
                    <label for="id_tipoAdquisicion" class="container-addForm--inputs__label">Tipo de adquisicion</label>
                    <div class="border">
                        {{form.tipoAdquisicion}}
                    </div>
                </div>
                <div class="container-addForm--inputs">
                    <label for="id_edicion" class="container-addForm--inputs__label">Edicion</label>
                    <div class="border">
                        {{form.edicion}}
                    </div>
                </div>
                <div class="container-addForm--inputs">
                    <label for="id_edicion" class="container-addForm--inputs__label">Puesto en circulacion</label>
                    <div class="border">
                        <div class="center-items">{{form.fechaEntrada}}</div>
                    </div>
                </div>
            </div>
            <div class="container-addForm--inputs space-between">
                <button class="container-form__button color-update">Modificar</button>
                <div class="center-items">
                    <label for="" class="">agregar fecha de ahora</label> 
                    <input class="style-check cursor-pointer" type="checkbox" name="dateToday" id="">
                </div>

            </div>
        </form>
    </div>
{% endblock %}

app/templates/books/books.html
{% extends 'base/base.html' %}

{% block content %}
    {% load static %}
    <header>
        {% include 'base/menu.html' %}
    </header>
    <main>

        <h1 class="title-page">Libros</h1>
        
        <section class="container background_filter">
            <div class="space-between ">
                <div class="leyenda">
                    <a href="{% url 'addBook' %}" class="ctaAdd">Añadir Libro</a>
                    <div class="leyenda-leyenda">
                        <label for="" class="" >no devueltos: {{noDevueltos.count}} </label>
                    </div>
                </div>
                    
                <form action="" class="center-items align-end">
                    <input type="text" name="search_filter" placeholder="Buscar" value="{{ request.GET.search_filter }}" class="search-box__input-filter">
                    <select name="libros" class="style-select" id="">
                        <option value="todos">Mostrar todos</option>
                        <option value="devueltos">Mostrar libros devueltos</option>
                        <option value="noDevueltos">Mostrar libros no devueltos</option>
                    </select>
                    <button class="color-update container-form__button">mostrar</button>
                </form>
            </div>
            <table class="position-relative">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>titulo</th>
                        <th>editorial</th>
                        <th>autor</th>
                        <th>edicion</th>
                        <th>disponible</th>
                        <th>detalles</th>
                    </tr>
                </thead>
                <tbody>
                    {% for book in books %}
                    <tr class="row">
                        <td class="content-list">{{book.id}}</td>
                        <td class="content-list">{{book}}</td>
                        <td class="content-list">{{book.editorial}}</td>
                        <td class="content-list">{{book.autor}}</td>
                        <td class="content-list">{{book.edicion}}</td>
                        {% if book.disponible %}
                        <td class="content-list">
                            <span class="libro-disponible">Disponible</span>
                        </td>
                        <td class="content-list">
                            <div class="center-items">
                                <a href="{% url 'bookDetails' book.id %}" class="ctaImg">
                                    <img src="{% static 'img/details.svg' %}" alt="" srcset="">
                                </a>
                            </div>
                        </td>
                    {% else %}
                        <td class="content-list">
                            <span class="error">No disponible</span>
                        </td>
                        <td class="content-list">
                            <div class="center-items">
                                <a href="{% url 'bookDetails' book.id %}" class="ctaImg">
                                    <img src="{% static 'img/details.svg' %}" alt="" srcset="">
                                </a>
                            </div>
                        </td>
                    {% endif %}
                    </tr>
                    {% endfor %}
                    </tbody>
            </table>
        </section>
    </main>
{% endblock content %}