registroBibliotecario/urls.py
from django.contrib import admin
from django.urls import path
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #--------------------USER MANAGE-------------------------
    path('', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    #-----------------------BOOKS-----------------------
    path('books/home/', views.books, name='books'),
    path('books/<int:idBook>/', views.bookDetails, name='bookDetails'),
    path('books/<int:idBook>/deleteBook/', views.deleteBook, name='deleteBook'),
    path('books/addBook/', views.addBook, name='addBook'),
    #-----------------READERS-------------
    path('readers/home/', views.readers, name='readers'),
    path('readers/<int:idReader>/', views.readerDetails, name='readerDetails'),
    path('readers/<int:idReader>/deleteReader/', views.deleteReader, name='deleteReader'),
    path('reader/addReader/', views.addReader, name='addReader'),
    #----------------LOANS-------------------------------
    path('loans/<int:idReader>/createLoan', views.createLoan, name='createLoan'),
    path('loans/home/', views.loans, name='loans'),
    path('loans/<int:idLoan>/', views.loanDetails, name='loanDetails'),
    path('loans/<int:idBook>/<int:idReader>/saveLoan/', views.saveLoan, name='saveLoan'),
    path('loans/<int:idLoan>/loanComeback/', views.loanComeback, name='loanComeback')
]

app/models.py
from django.db import models

class Books(models.Model):
    titulo = models.CharField(max_length=40)
    editorial = models.CharField(max_length=100)
    autor = models.CharField(max_length=30)
    fechaEntrada = models.DateField(null=True, blank=True)
    tipoAdquisicion = models.CharField(max_length=40)
    edicion = models.CharField(max_length=40)
    disponible = models.BooleanField(default=True)
    def __str__(self):
        return f'{self.titulo}'

class Readers(models.Model):
    nombres = models.CharField(max_length=60)
    apellidos = models.CharField(max_length=60)
    año = models.CharField(max_length=10, blank=True, null=True)
    seccion = models.CharField(max_length=20, blank=True, null=True)
    especialidad = models.CharField(max_length=40, blank=True, null=True)
    email = models.CharField(max_length=100)
    numeroTelefono = models.IntegerField()
    direccion = models.CharField(max_length=150, blank=True, null=True)
    esDocente = models.BooleanField(default=False)

    YEAR_CHOICES = (
        ('1','1'),
        ('2','2'),
        ('3','3'),
    )

    SECCION_CHOICES = (
        ('A', 'A'),
        ('B', 'B'),
        ('C','C'),
        ('D','D'),
        ('E','E')
    )

    ESPECIALIDADES_CHOICES = (
        ('Administrativo contable', 'Administrativo contable'),
        ('General', 'General'),
        ('Desarrollo de software', 'Desarrollo de software'),
        ('Serviempresa', 'Serviempresa'),
        ('Docente', 'Docente')
    )



class Loans(models.Model):
    idLibro = models.ForeignKey(Books, on_delete=models.CASCADE)
    idLector = models.ForeignKey(Readers, on_delete=models.CASCADE)
    fechaPrestamo = models.DateField(auto_now_add=True)
    fechaEntrega = models.DateField(null=True)
    estado = models.BooleanField(default=True)

app/templates/readers/addReader.html
{% extends 'base/base.html' %}

{% block content %}
    <header>
        <h1 class="title-page__addReader">Añadir Lector</h1>
    <div class="nav">
        <ul class="nav-box">
            <li >
                <a href="{% url 'readers' %}" class="nav-box__items item-menu-activate">Volver</a>
            </li>
        </ul>
    </div>
    </header>
    <div class="div-container-addForm background_filter"> 
        
        <form method="POST" action="{% url 'addReader' %}" class="container-addForm background_filter">
            {% csrf_token %}
            {{error}}
            <div class="content">
                <div class="container-addForm--inputs">
                    <label for="" class="container-addForm--inputs__label">Nombres</label>
                    <div class="border">
                        {{form.nombres}}
                    </div>
                </div>
                <div class="container-addForm--inputs">
                    <label for="" class="container-addForm--inputs__label">Apellidos</label>
                    <div class="border">
                        {{form.apellidos}}
                    </div>
                </div>
                <div class="container-addForm--inputs">
                    <label for="" class="container-addForm--inputs__label">Año</label>
                    <div class="border">
                        {{form.año}}
                    </div>
                </div>
                <div class="container-addForm--inputs">
                    <label for="" class="container-addForm--inputs__label">Seccion</label>
                    <div class="border">
                        {{form.seccion}}
                    </div>
                </div>
                <div class="container-addForm--inputs">
                    <label for="" class="container-addForm--inputs__label">Especialidad</label>
                    <div class="border">
                        {{form.especialidad}}
                    </div>
                </div>
                <div class="container-addForm--inputs">
                    <label for="" class="container-addForm--inputs__label">Email</label>
                    <div class="border">
                        {{form.email}}
                    </div>
                </div>
                <div class="container-addForm--inputs">
                    <label for="" class="container-addForm--inputs__label">Telefono</label>
                    <div class="border">
                        {{form.numeroTelefono}}
                    </div>
                </div>
                <div class="container-addForm--inputs">
                    <label for="" class="container-addForm--inputs__label">Direccion</label>
                    <div class="border">
                        {{form.direccion}}
                    </div>
                </div>
            </div>
            <div class="container-addForm--inputs">
                <button class="container-form__button color-update">crear</button>
            </div>
        </form>
    </div>

    
{% endblock %}

app/templates/readers/readerDetails.html
{% extends 'base/base.html' %}

{% block content %}
    {% load static %}
    
    <header>
        <h1 class="title-page__addReader">Detalles de {{reader.nombres}} </h1>
    <div class="nav">
        <ul class="nav-box">
            <li >
                <a href="{% url 'readers' %}" class="nav-box__items item-menu-activate">Volver</a>
            </li>
        </ul>
    </div>
    </header>
    <main>

        <div class="div-container-addForm background_filter"> 
            <form action="{% url 'deleteReader' reader.id %}" method="POST" class="align-end">
                {% csrf_token %}
                <button class="container-form__button color-delete center-items">
                    Eliminar            
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M6 7H5v13a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V7H6zm4 12H8v-9h2v9zm6 0h-2v-9h2v9zm.618-15L15 2H9L7.382 4H3v2h18V4z"></path></svg>
                </button>
            </form>
            <form method="POST" action="" class="container-addForm">
                {% csrf_token %}
                {{error}}
                <div class="content">
                    <div class="container-addForm--inputs">
                        <label for="" class="container-addForm--inputs__label">Nombres</label>
                        <div class="border">
                            {{form.nombres}}
                        </div>
                    </div>
                    <div class="container-addForm--inputs">
                        <label for="" class="container-addForm--inputs__label">Apellidos</label>
                        <div class="border">
                            {{form.apellidos}}
                        </div>
                    </div>
                    {% if  not reader.esDocente %}
                    <div class="container-addForm--inputs">
                        <label for="" class="container-addForm--inputs__label">Año</label>
                        <div class="border">
                            {{form.año}}
                        </div>
                    </div>
                    <div class="container-addForm--inputs">
                        <label for="" class="container-addForm--inputs__label">Seccion</label>
                        <div class="border">
                            {{form.seccion}}
                        </div>
                    </div>
                    {% endif %}
                    <div class="container-addForm--inputs">
                        <label for="" class="container-addForm--inputs__label">Especialidad</label>
                        <div class="border">
                            {{form.especialidad}}
                        </div>
                    </div>
                    <div class="container-addForm--inputs">
                        <label for="" class="container-addForm--inputs__label">Email</label>
                        <div class="border">
                            {{form.email}}
                        </div>
                    </div>
                    <div class="container-addForm--inputs">
                        <label for="" class="container-addForm--inputs__label">Telefono</label>
                        <div class="border">
                            {{form.numeroTelefono}}
                        </div>
                    </div>
                    <div class="container-addForm--inputs">
                        <label for="" class="container-addForm--inputs__label">Direccion</label>
                        <div class="border">
                            {{form.direccion}}
                        </div>
                    </div>
                </div>
                <div class="container-addForm--inputs">
                    <button class="container-form__button color-update center-items">Modificar</button>
                </div>
            </form>
            <div class="align-end">
                <p class="textOpenModal">Libros leidos {{books.count}} </p>
            </div>
            <section class="">
                <table>
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>titulo</th>
                            <th>editorial</th>
                            <th>autor</th>
                            <th>edicion</th>
                            <th>disponible</th>
                            <th>detalles</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for book in books %}
                        <tr class="row">
                            <td class="content-list">{{book.idLibro.id}}</td>
                            <td class="content-list">{{book.idLibro.titulo}}</td>
                            <td class="content-list">{{book.idLibro.editorial}}</td>
                            <td class="content-list">{{book.idLibro.autor}}</td>
                            <td class="content-list">{{book.idLibro.edicion}}</td>
                            {% if book.estado %}
                            <td class="content-list">
                                <span class="error">Libro no devuelto</span>
                            </td>
                            <td class="content-list">
                                <div class="center-items">
                                    <a href="{% url 'loanDetails' book.id %}" class="ctaImg">
                                        <img src="{% static 'img/details.svg' %}" alt="" srcset="">
                                    </a>
                                </div>
                            </td>
                            {% else %}
                            <td class="content-list">
                                <span class="libro-disponible">Libro devuelto</span>
                            </td>
                            <td class="content-list">
                                <div class="center-items">
                                    <a href="{% url 'loanDetails' book.id %}" class="ctaImg">
                                        <img src="{% static 'img/details.svg' %}" alt="" srcset="">
                                    </a>
                                </div>
                            </td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                        </tbody>
                </table>
            </section>
        </div>
    </main>
{% endblock %}

app/templates/readers/readers.html
{% extends 'base/base.html' %}

{% block content %}
    {% load static %}
    <header>
        {% include 'base/menu.html' %}
    </header>
    <main>
        <h1 class="title-page">Lectores</h1>
        <section class="container background_filter">
            <a href="{% url 'addReader' %}" class="ctaAdd">Añadir Lector</a>
            <table>
                <thead>
                    <tr>
                        <th class="content-list">ID</th>
                        <th class="content-list">nombres</th>
                        <th class="content-list">apellidos</th>
                        <th class="content-list">año</th>
                        <th class="content-list">especialidad</th>
                        <th class="content-list">seccion</th>
                        <th class="content-list">telefono</th>
                        <th class="content-list">libros leidos</th>
                    </tr>
                </thead>
                <tbody>
                    {% for reader in readers %}
                    <tr class="row"> 
                        <td class="content-list">{{reader.id}}</td>
                        <td class="content-list">{{reader.nombres}}</td>
                        <td class="content-list">{{reader.apellidos}}</td>
                        <td class="content-list">{{reader.año}}</td>
                        <td class="content-list">{{reader.especialidad}}</td>
                        <td class="content-list">{{reader.seccion}}</td>
                        <td class="content-list">{{reader.numeroTelefono}}</td>
                        <td class="content-list">{{reader.loans_set.count}}</td>
                        <td class="content-list center-items">
                            <a href="{% url 'createLoan' reader.id %}" class="cta">Crear Prestamo</a>
                            <a href="{% url 'readerDetails' reader.id %}"><img src="{% static './img/details.svg' %}" alt="" class="ctaImg"></a>
                        </td>
                    </tr>

                    {% endfor %}
                </tbody>
            </table>
        </section>

    </main>
{% endblock content %}